CREATE DATABASE IF NOT EXISTS GAMBLINGJS;

SHOW DATABASES;

USE GAMBLINGJS;

SHOW TABLES;

CREATE TABLE IF NOT EXISTS Users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

SELECT * FROM Users;